# Server Configuration
server:
  port: 8080


# Oracle settings and Pool Connection
spring:
  application:
    name: cadastro-lancamento
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: HR
    password: hr
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      minimum-idle: 2
      maximum-pool-size: 10
      pool-name: CadastroLancamentoApiPool
      idle-timeout: 9000
      isolate-internal-queries: true
      connection-test-query: SELECT 1 from DUAL
      connection-timeout: 18000
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        show_sql: true
        format_sql: true
        generate_statistics: false
        order_inserts: true
        order_updates: true
  liquibase:
    contexts: local
    change-log: classpath:db.changelog/master.xml
    enabled: true
  mvc: #incompatibilidade versão spring fox (paliativo)
    pathmatch:
      matching-strategy: ant-path-matcher

lancamento:
  topic:
    name: cadastro-lancamento
    dlq:
      name: cadastro-lancamento-dlt
logging:
  level:
    org:
      springframework:
        boot:
          autoconfigure: ERROR

  web: DEBUG


